"""initial tables

Revision ID: 0001_83cacded0d8a
Revises: 
Create Date: 2025-08-23 12:34:10.786711

"""
from typing import Sequence, Union
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_83cacded0d8a'
down_revision: Union[str, None] = None


def upgrade() -> None:
    schema = os.getenv("SCHEMA_SYNC_DB_SCHEMA_NAME", "schema_sync_schema")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_schemas',
    sa.Column('schema_uuid', sa.UUID(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid', 'schema_uuid'),
    schema=schema
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_firstname', sa.String(), nullable=False),
    sa.Column('user_lastname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('user_email'),
    schema=schema
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    schema = os.getenv("SCHEMA_SYNC_DB_SCHEMA_NAME", "schema_sync_schema")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema=schema)
    op.drop_table('output_schemas', schema=schema)
    # ### end Alembic commands ###
