"""initial tables

Revision ID: 0002_89cae74b82ad
Revises: 0001_83cacded0d8a
Create Date: 2025-08-24 13:03:45.955519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_89cae74b82ad'
down_revision: Union[str, None] = '0001_83cacded0d8a'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_password')
    # ### end Alembic commands ###
