"""initial tables

Revision ID: 0003_64c2209e1fbc
Revises: 0002_89cae74b82ad
Create Date: 2025-08-24 22:33:41.013043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_64c2209e1fbc'
down_revision: Union[str, None] = '0002_89cae74b82ad'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output_schemas', sa.Column('schema_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('output_schemas', 'schema_name')
    # ### end Alembic commands ###
